name: "Dog's Life (PAL)"
sha1: 19D81D0D8AA04AF0FFC12CDCC73FA7D6D5BEE3CB
options:
  basename: SCES_512.48
  target_path: elf/SCES_512.48
  elf_path: SCES_512.48
  base_path: ..
  platform: ps2
  compiler: EEGCC

  asm_path: asm
  asset_path: asm
  src_path: src
  build_path: build

  find_file_boundaries: False
  disasm_unknown: True
  named_regs_for_c_funcs: False
  use_gp_rel_macro_nonmatching: False
  ld_bss_is_noload: False
  generate_asm_macros_files: False
  migrate_rodata_to_functions: True
  make_full_disasm_for_code: False



  auto_decompile_empty_functions: False

  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: linkers/undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: linkers/undefined_syms_auto.txt
  ld_script_path: linkers/SCES_512.48.ld

  # Manually defined symbols
  symbol_addrs_path:
  - configs/sym.txt

  section_order: [".text", ".vutext", ".data", ".vudata", ".rodata", ".gcc_except_table", ".sdata", ".sbss", ".bss"]

  gp_value: 0x4546f0
  string_encoding: ASCII
  rodata_string_guesser_level: 2
  subalign: 4

segments:
  - [0, databin, elf_header]

  - name: main
    type: code
    start: 0x001000
    vram: 0x100000
    bss_size: 0x5047C
    align: 4
    subalign: 4
    subsegments:
      - [0x1000,   cpp, text]
      - [0x3B8F8, cpp, Dogs/Code/DustEffects]
      - [0x3C288, cpp, Dogs/Code/Fish]
      - [0x3D368, cpp, Dogs/Code/FlyingHat]
      - [0x3DE98, cpp, Dogs/Code/FootPrint]
      - [0x401F8, cpp, Dogs/Code/LevelGate]
      - [0x40F10, cpp, text_0013FF10] # Light?
      - [0x43FB8, cpp, text_00142FB8] # Motorbike?
      - [0x45BC8, cpp, text_00144BC8] # ParticleSystem
      - [0x4B110, cpp, text_0014A110] # Person
      - [0x51120,  cpp, text_00150120]
      - [0x53DD0, cpp, text_00152DD0]
      - [0x613D0, cpp, text_001603D0]
      - [0x6A1B8, cpp, text_001691B8]
      - [0xA0570,  cpp, Dogs/Code/Console]
      - [0xAC700,  cpp, text_001AB700] # containers (pram, basketball net)
      - [0xAE138,  cpp, Dogs/Code/Creatres]
      - [0xAE378,  cpp, text_001AD378]
      #- [0xB0470,  cpp, text_001AF470] # Objects 3D related
      #- [0xB17A8,  cpp, text_001B07A8] # Textures related
      #- [0xB2F70,  cpp, text_001B1F70]
      #- [0xD92A0,  cpp, text_001D82A0]


      - [0xE24F8,  cpp, text_001E14F8]
      - [0xE6648, cpp, Dogs/Code/Levelres]

      - [0xE6870, cpp, text_001E5870]
      - [0xE7FF0, cpp, text_001E6FF0]
      - [0x1411D8, cpp, text_002401D8]
      - [0x14CA70, cpp, FGDK3/ResLibs/SoundRes/Code/SoundRes]
      - [0x14CED8, cpp, text_0024BED8]
      - [0x16B940, cpp, FGDK3/Code/Playstation2/TimSrv]
      - [0x16C2A8, cpp, FGDK3/Code/ThrowCat]
      - [0x16C710, cpp, FGDK3/Code/Playstation2/Thread]
      - [0x16D380, cpp, FGDK3/Code/TextRes]
      - [0x16D5C8, cpp, text_0026C5C8]
      - [0x16E178, cpp, text_0026D178]
      - [0x17A880, cpp, text_00279880]

      #- [0x16D5C8, cpp, FGDK3/Code/StdMem]
      - [0x17FA98, cpp, FGDK3/Code/Playstation2/MusicRes]
      - [0x17FD98, cpp, FGDK3/Code/Playstation2/Music] # -O0
      - [0x189B30, cpp, text_00288B30] # Sound.c?


      #- [0x1900B0, cpp, text_0028F0B0]

      - [0x1D3D80, cpp, FGDK3/Code/Playstation2/GameShell] # -O0 - Guessed filepath and name
      - [0x1D4598, cpp, text_002D3598]
      - [0x1F82C0, cpp, FGDK3/Code/InpUtil]
      - [0x1F8F28, cpp, FGDK3/Code/Playstation2/InpMouse]
      - [0x1F9820, cpp, FGDK3/Code/Playstation2/InpKeybd]
      - [0x1F9F00, cpp, FGDK3/Code/Playstation2/InpJoys1]
      - [0x1FA408, cpp, FGDK3/Code/Playstation2/InpJoy5]
      - [0x1FA528, cpp, FGDK3/Code/Inpevent]
      - [0x1FC878, cpp, FGDK3/Code/Inpdev]
      - [0x1FCD40, cpp, text_002FBD40]
      - [0x1FCFF0, cpp, FGDK3/Code/Playstation2/Controller]
      - [0x1FDF70, cpp, text_002FCF70] # -O0
      - [0x20A778, cpp, text_00309778]
      - [0x211BE8, cpp, text_00310BE8]
      #- [0x211BE8, cpp, FGDK3/Code/FileSystem_Zip]
      #- [cpp, FGDK3/Code/Playstation2/File_FileDescriptor]
      - [0x216F28, cpp, text_00315F28] # zlib functions
      # 0x216F28 inflate.c
      - [0x219FD0, cpp, FGDK3/ResLibs/AnimRes/Code/AnimRes]
      - [0x21A340, cpp, FGDK3/ResLibs/ScriptRes/Code/ScriptThread]
      - [0x21D940, cpp, FGDK3/ResLibs/ScriptRes/Code/ScriptRes]
      - [0x21FEA0, cpp, FGDK3/ResLibs/ShapeRes/Code/ShapeRes]
      - [0x2201B8, cpp, FGDK3/ResLibs/LandscapeRes/Code/LandscapeRes]
      - [0x220478, cpp, FGDK3/ResLibs/TextureRes/Code/TextureRes]

      - [0x220C50, cpp, text_0031FC50]
      - [0x228FD0, asm, sce/eecdvd] # libcdvd
      - [0x22AC38, asm, sce/text_00329C38] # libgraph
      - [0x22C448, asm, sce/libdma] # libdma
      - [0x22CC90, cpp, text_0032BC90] # libdev
      - [0x22DD90, asm, sce/libpad]
      - [0x22F128, asm, sce/libgifpk]

      - [0x22F468, asm, sce/sdr_main] # libsdr
      - [0x22F868, asm, sce/sdr_cb]

      - [0x22FA48, asm, sce/libmc]
      - [0x231240, asm, sce/libscf]
      - [0x231930, cpp, text_00330930]
      - [0x235BD0, cpp, text_00334BD0]


      - [0x24D300, textbin, vutext]
      - [0x25A680, data, text]
      - [0x290EC0, data, vudata]
      - [0x290F00, .rodata, text]
      - [0x2A9370, .rodata, Dogs/Code/DustEffects]
      - [0x2A9760, .rodata, Dogs/Code/Fish]
      - [0x2AAFD0, .rodata, Dogs/Code/FlyingHat]
      - [0x2AC6C8, .rodata, Dogs/Code/FootPrint]
      - [0x2AE1C8, .rodata, Dogs/Code/LevelGate]
      - [0x2AE620, .rodata, text_0013FF10]
      - [0x2AF160, .rodata, text_00142FB8]
      - [0x2B0878, .rodata, text_00144BC8]
      - [0x2B2CF0, .rodata, text_0014A110]

      #- [0x2A2C48, .rodata, Dogs/Code/Cloth]
      #- [0x29A148, .rodata, Dogs/Code/BoneGod]
      - [0x2B2DB0, .rodata, text_00150120]
      - [0x2BBDB8, .rodata, text_00152DD0]
      - [0x2BE2F8, .rodata, text_001603D0]
      - [0x2C0A30, .rodata, text_001691B8]
      - [0x2D5B18, .rodata, Dogs/Code/Console]
      - [0x2D7AA0, .rodata, text_001AB700]
      - [0x2DBF80, .rodata, Dogs/Code/Creatres]
      - [0x2DC138, .rodata, text_001AD378]
      - [0x2E6400, .rodata, text_001E14F8]

      - [0x2E6640, .rodata, Dogs/Code/Levelres]


      - [0x2E67C8, .rodata, text_001E5870]

      - [0x2E6CF0, .rodata, text_001E6FF0]
      - [0x333BB0, .rodata, text_002401D8]
      - [0x333f18, .rodata, FGDK3/ResLibs/SoundRes/Code/SoundRes]
      - [0x334058, .rodata, text_0024BED8]
      - [0x33C470, .rodata, FGDK3/Code/Playstation2/TimSrv]
      - [0x33C4F8, .rodata, FGDK3/Code/ThrowCat]
      - [0x33C610, .rodata, FGDK3/Code/Playstation2/Thread]
      - [0x33C820, .rodata, FGDK3/Code/TextRes]

      - [0x33C8E0, .rodata, text_0026C5C8]
      - [0x33C978, .rodata, text_0026D178]

      - [0x33D7A8, .rodata, text_00279880]

      #-[0x33C8E0, .rodata, FGDK3/Code/StdMem]
      #-[0x33C918, .rodata, FGDK3/Code/StdInit]
      #-[0x33C978, .rodata, FGDK3/Code/Playstation2/SoundManager]
      #-[0x33C9E0, .rodata, FGDK3/Code/Playstation2/Sound]
      #-[0x33CAD0, .rodata, FGDK3/Code/Playstation2/sifManager]
      #-[0x33D7A8, .rodata, FGDK3/Code/NavGraphRes]
      - [0x33D968, .rodata, FGDK3/Code/Playstation2/MusicRes]
      - [0x33DA50, .rodata, FGDK3/Code/Playstation2/Music]
      #-[0x33E030, .rodata, sound]
      - [0x33E030, .rodata, text_00288B30]

      #- [0x33FA98, .rodata, text_0028F0B0]

      #-[0x33FA98, .rodata, FGDK3/Code/Playstation2/IOPMem]
      - [0x343CE8, .rodata, FGDK3/Code/Playstation2/GameShell]
      - [0x343D68, .rodata, text_002D3598]
      #CLIOpts 345658
      #WalkerComponents 345800
      #UtilAnimComps
      #IKComponents
      #AnimVarComponents
      #AnimPosComponents
      #AnimateTimeBases
      #Animate

      - [0x347AA8, .rodata, FGDK3/Code/InpUtil]
      - [0x347AA8, .rodata, FGDK3/Code/Playstation2/InpMouse]
      - [0x347D88, .rodata, FGDK3/Code/Playstation2/InpKeybd]
      - [0x347EA8, .rodata, FGDK3/Code/Playstation2/InpJoys1]
      - [0x347FA8, .rodata, FGDK3/Code/Playstation2/InpJoy5]
      - [0x347FF0, .rodata, FGDK3/Code/Inpevent]
      - [0x348110, .rodata, FGDK3/Code/Inpdev]
      - [0x3481A0, .rodata, text_002FBD40]
      - [0x348290, .rodata, FGDK3/Code/Playstation2/Controller]
      #File_Memcard
      #File_CD
      #File
      #Playstation2/File
      #FileSystem_Zip
      #File_FileDescriptor
      - [0x348390, .rodata, text_002FCF70]
      - [0x348CD0, .rodata, text_00309778]
      #- [0x349040, .rodata, FGDK3/Code/FileSystem_Zip]
      - [0x349040, .rodata, text_00310BE8]
      - [0x349540, .rodata, text_00315F28] # zlib stuff?
      - [0x349C08, .rodata, FGDK3/ResLibs/AnimRes/Code/AnimRes]
      - [0x349DF0, .rodata, FGDK3/ResLibs/ScriptRes/Code/ScriptThread]
      - [0x34A2E0, .rodata, FGDK3/ResLibs/ScriptRes/Code/ScriptRes]
      - [0x34A820, .rodata, FGDK3/ResLibs/ShapeRes/Code/ShapeRes]
      - [0x34A9A8, .rodata, FGDK3/ResLibs/LandscapeRes/Code/LandscapeRes]
      - [0x34AB88, .rodata, FGDK3/ResLibs/TextureRes/Code/TextureRes]
      - [0x34AC70, .rodata, text_0031FC50]
      - [0x34B180, rodata, sce/eecdvd] # libcdvd
      - [0x34B490, rodata, sce/text_00329C38] # libgraph


      - [0x34B6D8, rodata, sce/libdma]
      - [0x34B750, .rodata, text_0032BC90] # libdev
      - [0x34B788, rodata, sce/libpad]

      - [0x34B8E0, rodata, sce/sdr_main] # libsdr
      - [0x34B908, rodata, sce/sdr_cb]

      - [0x34B930, rodata, sce/libmc]
      - [0x34B9B8, rodata, sce/libscf]
      - [0x34B9E0, .rodata, text_00330930]
      - [0x34C0E8, .rodata, text_00334BD0]



      - [0x34D580, gcc_except_table]
      - [0x34D700, sdata]
      - {start: 0x354280, type: sbss, vram: 0x00453280}
      - {start: 0x354A80, type: bss,  vram: 0x00453A80}

  - [0x360F18, databin]
  - [0x362668]
