name: "Dog's Life (PAL)"
sha1: 19D81D0D8AA04AF0FFC12CDCC73FA7D6D5BEE3CB
options:
  basename: SCES_512.48
  target_path: elf/SCES_512.48
  elf_path: SCES_512.48
  base_path: ..
  platform: ps2
  compiler: EEGCC

  asm_path: asm
  asset_path: asm
  src_path: src
  build_path: build

  find_file_boundaries: False
  disasm_unknown: True
  named_regs_for_c_funcs: False
  use_gp_rel_macro_nonmatching: False
  ld_bss_is_noload: False
  generate_asm_macros_files: False
  migrate_rodata_to_functions: True
  make_full_disasm_for_code: False



  auto_decompile_empty_functions: False

  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: linkers/undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: linkers/undefined_syms_auto.txt
  ld_script_path: linkers/SCES_512.48.ld

  # Manually defined symbols
  symbol_addrs_path:
  - configs/sym.txt

  section_order: [".text", ".vutext", ".data", ".vudata", ".rodata", ".gcc_except_table", ".sdata", ".sbss", ".bss"]

  gp_value: 0x4546f0
  string_encoding: ASCII
  rodata_string_guesser_level: 2
  subalign: 4

segments:
  - [0, databin, elf_header]

  - name: main
    type: code
    start: 0x001000
    vram: 0x100000
    bss_size: 0x5047C
    align: 4
    subalign: 4
    subsegments:
      #- [0x1000, cpp, text]
      - [0x1000, asm, text]
      - [0x1100, cpp, Dogs/Code/AnimatedObject]
      - [0x5338, cpp, Dogs/Code/Aperture]
      - [0x5B08, cpp, Dogs/Code/Basket]
      - [0x7220, cpp, Dogs/Code/Bird]
      - [0x8760, cpp, Dogs/Code/BoneGod]
      - [0x9B68, cpp, Dogs/Code/Boulder]
      - [0xAF40, cpp, Dogs/Code/Button]
      - [0xB718, cpp, Dogs/Code/Camera]
      - [0x23F50, cpp, Dogs/Code/Car]
      - [0x25EF8, cpp, Dogs/Code/Cloth]
      - [0x28D30, cpp, Dogs/Code/DiggablePatch]
      - [0x2A2C8, cpp, Dogs/Code/DiggingRace]

      - [0x2DD30, cpp, Dogs/Code/Dog]
      - [0x3B8F8, cpp, Dogs/Code/DustEffects]
      - [0x3C288, cpp, Dogs/Code/Fish]
      - [0x3D368, cpp, Dogs/Code/FlyingHat]
      - [0x3DE98, cpp, Dogs/Code/FootPrint]
      - [0x401F8, cpp, Dogs/Code/LevelGate]
      - [0x40D48, cpp, Dogs/Code/Lights]
      - [0x43FB8, cpp, Dogs/Code/Motorbike]
      - [0x45BC8, cpp, Dogs/Code/ParticleSystem]
      - [0x4B110, cpp, Dogs/Code/Person]
      - [0x4E058, cpp, Dogs/Code/PlaceHolder]
      - [0x4E410, cpp, Dogs/Code/PlayerDog]
      - [0x50640, cpp, Dogs/Code/Rat]
      - [0x51F30, cpp, Dogs/Code/SaveKennel]
      - [0x53DD0, cpp, Dogs/Code/Scent]
      - [0x5B528, cpp, Dogs/Code/ScentMarkingGame]
      - [0x613D0, cpp, Dogs/Code/Selector]
      - [0x62068, cpp, Dogs/Code/SimObj]


      - [0x6A1B8, cpp, Dogs/Code/Skidoo]
      - [0x6BEE0, cpp, Dogs/Code/SkiLiftSeat]
      - [0x6CD80, cpp, Dogs/Code/Slidable]
      - [0x6E910, cpp, Dogs/Code/SmallThing]
      - [0x72368, cpp, Dogs/Code/Smell]
      - [0x73A50, cpp, Dogs/Code/Snowball]
      - [0x741F8, cpp, Dogs/Code/SoundCreature]
      - [0x748D8, cpp, Dogs/Code/SphereObj]
      - [0x78788, cpp, Dogs/Code/SwingBridge]
      - [0x79658, cpp, Dogs/Code/TugOfWar]
      - [0x7E340, cpp, Dogs/Code/WaterSplash]
      - [0x811A0, cpp, Dogs/Code/WheeledVehicle]
      - [0x82948, cpp, Dogs/Code/WorldObj]
      - [0x898E0, cpp, Dogs/Code/Zone]
      - [0x8B208, cpp, Dogs/Code/ActorPersist]
      - [0x8CB70, cpp, text_0018BB70]
      - [0x8D748, cpp, Dogs/Code/BookMetaphor]
      - [0x9F5A0, cpp, Dogs/Code/Bounce]
      - [0xA0570, cpp, Dogs/Code/Console]
      - [0xAC700, cpp, Dogs/Code/Containers]
      - [0xAE138, cpp, Dogs/Code/Creatres]
      - [0xAE378, cpp, Dogs/Code/DogScript]
      - [0xB0470, cpp, Dogs/Code/Element3D]
      - [0xB17A8, cpp, text_001B07A8]
      - [0xB2F70, cpp, Dogs/Code/Game]
      - [0xD92A0, cpp, Dogs/Code/GameState]
      - [0xDB3A0, cpp, Dogs/Code/Gameutil]
      - [0xDE5F0, cpp, Dogs/Code/HitTri]
      - [0xDF378, cpp, Dogs/Code/Landscape]
      - [0xE6198, cpp, text_001E5198] # actual start of levelres?

      - [0xE6648, cpp, Dogs/Code/Levelres]

      - [0xE6870, cpp, Dogs/Code/Playstation2/Main]
      - [0xE6C98, cpp, Dogs/Code/Mien]
      - [0xE7FF0, cpp, Dogs/Code/MusicServices]
      - [0xE82D8, cpp, Dogs/Code/NavClient]
      - [0xEB608, cpp, Dogs/Code/Objects]
      - [0xED630, cpp, Dogs/Code/Objtable]
      - [0xEE1D8, cpp, Dogs/Code/Paused]
      - [0xEE440, cpp, Dogs/Code/Platform]
      - [0xF18F8, cpp, Dogs/Code/Player]
      - [0xF84B8, cpp, Dogs/Code/PlayerAnim]
      - [0xF9138, cpp, text_001F8138]
      - [0xFD108, cpp, text_001FC0E8]
      - [0xFD440, cpp, text_001FC440]
      - [0xFF088, cpp, Dogs/Code/SaveGameManager]
      - [0x1042D8, cpp, text_002032D8]
      - [0x104A98, cpp, text_00203A98]
      - [0x1292D8, cpp, Dogs/Code/SlidableBlockPuzzle]
      - [0x12A7F0, cpp, Dogs/Code/SpecialIKComponents]
      - [0x12BD48, cpp, Dogs/Code/SpeechAni]
      - [0x12E4E8, cpp, Dogs/Code/Title]
      - [0x12FA50, cpp, Dogs/Code/Trail]
      - [0x130AC8, cpp, Dogs/Code/Travel]
      - [0x1365E0, cpp, Dogs/Code/Visual]
      - [0x13F698, cpp, text_0023E698]
      - [0x1431F8, cpp, text_002421F8]
      #- [0x1411D8, cpp, text_002401D8]
      - [0x14CA70, cpp, FGDK3/ResLibs/SoundRes/Code/SoundRes]
      - [0x14CED8, cpp, FGDK3/Code/Widget]
      - [0x161028, cpp, text_00260028]
      - [0x1617A0, cpp, text_002607A0]
      - [0x16B940, cpp, FGDK3/Code/Playstation2/TimSrv]
      - [0x16C2A8, cpp, FGDK3/Code/ThrowCat]
      - [0x16C710, cpp, FGDK3/Code/Playstation2/Thread]
      - [0x16D380, cpp, FGDK3/Code/TextRes]
      - [0x16D5C8, cpp, FGDK3/Code/StdMem]
      - [0x16E178, cpp, FGDK3/Code/Playstation2/SoundManager]
      - [0x16EF68, cpp, FGDK3/Code/Playstation2/Sound]
      - [0x170BA0, cpp, FGDK3/Code/Playstation2/sifManager]
      - [0x170FB8, cpp, text_0026FFB8] # shape.cpp?
      - [0x172A20, cpp, text_00271A20]
      - [0x176FF8, cpp, text_00275FF8]
      - [0x1785D0, cpp, text_002775D0] # beginning of RelRecv.cpp?
      - [0x17A880, cpp, FGDK3/Code/NavGraphRes] # navgraph functions

      #- [0x16D5C8, cpp, FGDK3/Code/StdMem]
      - [0x17FA98, cpp, FGDK3/Code/Playstation2/MusicRes]
      - [0x17FD98, cpp, FGDK3/Code/Playstation2/Music] # -O0
      - [0x189B30, cpp, text_00288B30] # Sound.c?
      #- [0x1900B0, cpp, text_0028F0B0]
      - [0x190150, cpp, text_0028F150]
      - [0x191F58, cpp, text_00290F58]
      - [0x1975D0, cpp, FGDK3/Code/Location]
      - [0x197670, cpp, FGDK3/Code/Playstation2/IOPMem]
      - [0x198578, cpp, text_00297578]
      - [0x1A2D88, cpp, text_002A1D88]
      - [0x1A59A0, cpp, FGDK3/Code/Playstation2/GE_RenderHardware]
      - [0x1A6350, cpp, text_002A5350]
      - [0x1AEC40, cpp, text_002ADC40]
      - [0x1CB560, cpp, text_002CA560]
      - [0x1D3D80, cpp, FGDK3/Code/GameShell] # -O0 - Guessed filepath and name
      - [0x1D4598, cpp, text_002D3598]
      - [0x1D7BE8, cpp, text_002D6BE8]
      - [0x1DA560, cpp, text_002D9560]
      - [0x1DBB38, cpp, FGDK3/Code/DrawShape]
      - [0x1DF720, cpp, text_002DE720]
      - [0x1E0A70, cpp, FGDK3/Code/CLIOpts]
      - [0x1E1558, cpp, FGDK3/Code/WalkerComponents]
      - [0x1E7550, cpp, FGDK3/Code/UtilAnimComps]
      - [0x1E85B0, cpp, FGDK3/Code/IKComponents]
      - [0x1E8B08, cpp, FGDK3/Code/BoneManager]
      - [0x1EE2C8, cpp, FGDK3/Code/AnimVarComponents]
      - [0x1EE9C0, cpp, text_002ED9C0]
      - [0x1EEBD0, cpp, FGDK3/Code/AnimPosComponents]
      - [0x1F0738, cpp, FGDK3/Code/AnimateTimeBases]
      - [0x1F4EF0, cpp, FGDK3/Code/Animate]
      - [0x1F82C0, cpp, FGDK3/Code/InpUtil]
      - [0x1F8F28, cpp, FGDK3/Code/Playstation2/InpMouse]
      - [0x1F9820, cpp, FGDK3/Code/Playstation2/InpKeybd]
      - [0x1F9F00, cpp, FGDK3/Code/Playstation2/InpJoys1]
      - [0x1FA408, cpp, FGDK3/Code/Playstation2/InpJoy5]
      - [0x1FA528, cpp, FGDK3/Code/Inpevent]
      - [0x1FC878, cpp, FGDK3/Code/Inpdev]
      - [0x1FCD40, cpp, text_002FBD40]
      - [0x1FCFF0, cpp, FGDK3/Code/Playstation2/Controller]
      - [0x1FDF70, cpp, text_002FCF70] # -O0
      - [0x203D50, cpp, FGDK3/Code/Playstation2/File_CD]
      - [0x205B48, cpp, FGDK3/Code/File]
      - [0x208D30, cpp, text_00307D30]
      - [0x20A778, cpp, text_00309778]
      - [0x20BC08, cpp, FGDK3/Code/StringUtils]
      - [0x20C698, cpp, FGDK3/Code/ShapeParams]
      - [0x211BE8, cpp, FGDK3/Code/FileSystem_Zip]
      #- [cpp, FGDK3/Code/Playstation2/File_FileDescriptor]
      - [0x216F28, cpp, text_00315F28] # zlib functions
      # 0x216F28 inflate.c
      - [0x219FD0, cpp, FGDK3/ResLibs/AnimRes/Code/AnimRes]
      - [0x21A340, cpp, FGDK3/ResLibs/ScriptRes/Code/ScriptThread]
      - [0x21D940, cpp, FGDK3/ResLibs/ScriptRes/Code/ScriptRes]
      - [0x21FEA0, cpp, FGDK3/ResLibs/ShapeRes/Code/ShapeRes]
      - [0x2201B8, cpp, FGDK3/ResLibs/LandscapeRes/Code/LandscapeRes]
      - [0x220478, cpp, FGDK3/ResLibs/TextureRes/Code/TextureRes]

      - [0x220C50, cpp, text_0031FC50]
      - [0x228FD0, asm, sce/eecdvd] # libcdvd
      - [0x22AC38, asm, sce/text_00329C38] # libgraph
      - [0x22C448, asm, sce/libdma] # libdma
      - [0x22CC90, cpp, text_0032BC90] # libdev
      - [0x22DD90, asm, sce/libpad]
      - [0x22F128, asm, sce/libgifpk]

      - [0x22F468, asm, sce/sdr_main] # libsdr
      - [0x22F868, asm, sce/sdr_cb]

      - [0x22FA48, asm, sce/libmc]
      - [0x231240, asm, sce/libscf]
      - [0x231930, cpp, text_00330930]
      - [0x235BD0, cpp, text_00334BD0]
      - [0x24D300, textbin, vutext]
      - [0x25A680, data, text]
      - [0x290EC0, data, vudata]
      - [0x290F00, .rodata, Dogs/Code/AnimatedObject]
      - [0x296DD0, .rodata, Dogs/Code/Aperture]
      - [0x296FF0, .rodata, Dogs/Code/Basket]
      - [0x2988D8, .rodata, Dogs/Code/Bird]
      - [0x29A148, .rodata, Dogs/Code/BoneGod]
      - [0x29B868, .rodata, Dogs/Code/Boulder]
      - [0x29D150, .rodata, Dogs/Code/Button]
      - [0x29E888, .rodata, Dogs/Code/Camera]
      - [0x2A1490, .rodata, Dogs/Code/Car]
      - [0x2A2B90, .rodata, Dogs/Code/Cloth]
      - [0x2A4588, .rodata, Dogs/Code/DiggablePatch]
      - [0x2A5D98, .rodata, Dogs/Code/DiggingRace]
      - [0x2A7660, .rodata, Dogs/Code/Dog]
      - [0x2A9370, .rodata, Dogs/Code/DustEffects]
      - [0x2A9760, .rodata, Dogs/Code/Fish]
      - [0x2AAFD0, .rodata, Dogs/Code/FlyingHat]
      - [0x2AC6C8, .rodata, Dogs/Code/FootPrint]
      - [0x2AE1C8, .rodata, Dogs/Code/LevelGate]
      - [0x2AE620, .rodata, Dogs/Code/Lights]
      - [0x2AF160, .rodata, Dogs/Code/Motorbike]
      - [0x2B0878, .rodata, Dogs/Code/ParticleSystem]
      - [0x2B2CF0, .rodata, Dogs/Code/Person]
      - [0x2B4740, .rodata, Dogs/Code/PlaceHolder]
      - [0x2B5E18, .rodata, Dogs/Code/PlayerDog]
      - [0x2B8DD0, .rodata, Dogs/Code/Rat]
      - [0x2BA5F8, .rodata, Dogs/Code/SaveKennel]
      - [0x2BBDB8, .rodata, Dogs/Code/Scent]
      - [0x2BC728, .rodata, Dogs/Code/ScentMarkingGame]
      - [0x2BE2F8, .rodata, Dogs/Code/Selector]
      - [0x2BFA88, .rodata, Dogs/Code/SimObj]


      - [0x2C0A30, .rodata, Dogs/Code/Skidoo]
      - [0x2C21F0, .rodata, Dogs/Code/SkiLiftSeat]
      - [0x2C3900, .rodata, Dogs/Code/Slidable]
      - [0x2C5290, .rodata, Dogs/Code/SmallThing]
      - [0x2C6C20, .rodata, Dogs/Code/Smell]
      - [0x2C6FB0, .rodata, Dogs/Code/Snowball]
      - [0x2C8780, .rodata, Dogs/Code/SoundCreature]
      - [0x2C8AD8, .rodata, Dogs/Code/SphereObj]
      - [0x2CA558, .rodata, Dogs/Code/SwingBridge]
      - [0x2CBC48, .rodata, Dogs/Code/TugOfWar]
      - [0x2CEDC0, .rodata, Dogs/Code/WaterSplash]
      - [0x2CF490, .rodata, Dogs/Code/WheeledVehicle]
      - [0x2D0BF8, .rodata, Dogs/Code/WorldObj]
      - [0x2D2C20, .rodata, Dogs/Code/Zone]
      - [0x2D3470, .rodata, Dogs/Code/ActorPersist]
      - [0x2D37C0, .rodata, text_0018BB70]
      - [0x2D3B58, .rodata, Dogs/Code/BookMetaphor]
      - [0x2D5780, .rodata, Dogs/Code/Bounce]
      - [0x2D59E8, .rodata, Dogs/Code/Console]
      - [0x2D7AA0, .rodata, Dogs/Code/Containers]
      - [0x2DBF80, .rodata, Dogs/Code/Creatres]
      - [0x2DC138, .rodata, Dogs/Code/DogScript]
      - [0x2DC688, .rodata, Dogs/Code/Element3D]
      - [0x2DCA50, .rodata, text_001B07A8]
      - [0x2DCB38, .rodata, Dogs/Code/Game]
      - [0x2E41B8, .rodata, Dogs/Code/GameState]
      - [0x2E4740, .rodata, Dogs/Code/Gameutil]
      - [0x2E4AD0, .rodata, Dogs/Code/HitTri]
      - [0x2E6218, .rodata, Dogs/Code/Landscape]
      - [0x2E6640, .rodata, Dogs/Code/Levelres]
      - [0x2E67C8, .rodata, Dogs/Code/Playstation2/Main]
      - [0x2E6900, .rodata, Dogs/Code/Mien]
      - [0x2E6CF0, .rodata, Dogs/Code/MusicServices]
      - [0x2E6F88, .rodata, Dogs/Code/NavClient]
      - [0x2E7200, .rodata, Dogs/Code/Objects]
      - [0x2E74F8, .rodata, Dogs/Code/Objtable]
      - [0x2E7708, .rodata, Dogs/Code/Paused]
      - [0x2E7C78, .rodata, Dogs/Code/Platform]
      - [0x2EAB28, .rodata, Dogs/Code/Player]
      - [0x2EB1B0, .rodata, Dogs/Code/PlayerAnim]
      - [0x2EB398, .rodata, text_001F8138]
      - [0x2EC868, .rodata, text_001FC0E8]
      - [0x2EC868, .rodata, text_001FC440]
      - [0x30CCE8, .rodata, Dogs/Code/SaveGameManager]
      - [0x30D700, .rodata, text_002032D8]
      - [0x30D878, .rodata, text_00203A98]
      - [0x32D050, .rodata, Dogs/Code/SlidableBlockPuzzle]
      - [0x32EB18, .rodata, Dogs/Code/SpecialIKComponents]
      - [0x32EE48, .rodata, Dogs/Code/SpeechAni]
      - [0x32F630, .rodata, Dogs/Code/Title]
      - [0x32FCF8, .rodata, Dogs/Code/Trail]
      - [0x331498, .rodata, Dogs/Code/Travel]
      - [0x332288, .rodata, Dogs/Code/Visual]
      - [0x333510, .rodata, text_0023E698]
      - [0x333560, .rodata, text_002421F8]
      #- [0x333BB0, .rodata, text_002401D8]
      - [0x333f18, .rodata, FGDK3/ResLibs/SoundRes/Code/SoundRes]
      - [0x334058, .rodata, FGDK3/Code/Widget]
      - [0x338560, .rodata, text_00260028]
      - [0x3385A8, .rodata, text_002607A0]
      - [0x33C470, .rodata, FGDK3/Code/Playstation2/TimSrv]
      - [0x33C4F8, .rodata, FGDK3/Code/ThrowCat]
      - [0x33C610, .rodata, FGDK3/Code/Playstation2/Thread]
      - [0x33C820, .rodata, FGDK3/Code/TextRes]

      - [0x33C8E0, .rodata, FGDK3/Code/StdMem]
      #-[0x33C918, .rodata, FGDK3/Code/StdInit]
      - [0x33C978, .rodata, FGDK3/Code/Playstation2/SoundManager]
      - [0x33C9E0, .rodata, FGDK3/Code/Playstation2/Sound]
      - [0x33CAD0, .rodata, FGDK3/Code/Playstation2/sifManager]
      - [0x33CBC0, .rodata, text_0026FFB8]
      - [0x33CE40, .rodata, text_00271A20] # SavedGame
      #- [0x33CE68, .rodata, FGDK3/Code/Playstation2/RunPath]
      #- [0x33CEE0]
      - [0x33D280, .rodata, text_00275FF8]
      - [0x33D2B0, .rodata, text_002775D0]
      - [0x33D7A8, .rodata, FGDK3/Code/NavGraphRes]
      - [0x33D968, .rodata, FGDK3/Code/Playstation2/MusicRes]
      - [0x33DA50, .rodata, FGDK3/Code/Playstation2/Music]
      #-[0x33E030, .rodata, sound]
      - [0x33E030, .rodata, text_00288B30]
      #- [0x33FA98, .rodata, text_0028F0B0]
      #-[0x33FA98, .rodata, FGDK3/Code/Playstation2/IOPMem]
      - [0x33FAF0, .rodata, text_00290F58]
      - [0x33FC60, .rodata, FGDK3/Code/Location]
      - [0x33FC70, .rodata, FGDK3/Code/Playstation2/IOPMem]
      - [0x33FE30, .rodata, text_00297578]
      - [0x340250, .rodata, text_002A1D88]
      - [0x340320, .rodata, FGDK3/Code/Playstation2/GE_RenderHardware]
      - [0x340490, .rodata, text_002A5350]
      - [0x340970, .rodata, text_002ADC40]
      - [0x3438E0, .rodata, text_002CA560]


      - [0x343CE8, .rodata, FGDK3/Code/GameShell]
      - [0x343D68, .rodata, text_002D3598]
      - [0x344B70, .rodata, text_002D6BE8]
      - [0x344DC8, .rodata, text_002D9560]
      - [0x345438, .rodata, FGDK3/Code/DrawShape]
      - [0x345498, .rodata, text_002DE720]
      - [0x345658, .rodata, FGDK3/Code/CLIOpts]
      - [0x345800, .rodata, FGDK3/Code/WalkerComponents]
      - [0x346040, .rodata, FGDK3/Code/UtilAnimComps]
      - [0x346100, .rodata, FGDK3/Code/IKComponents]
      - [0x3462B0, .rodata, FGDK3/Code/BoneManager]
      - [0x346350, .rodata, FGDK3/Code/AnimVarComponents]
      - [0x346578, .rodata, text_002ED9C0]
      - [0x346590, .rodata, FGDK3/Code/AnimPosComponents]
      - [0x346CE8, .rodata, FGDK3/Code/AnimateTimeBases]
      - [0x347610, .rodata, FGDK3/Code/Animate]

      - [0x347AA8, .rodata, FGDK3/Code/InpUtil]
      - [0x347AA8, .rodata, FGDK3/Code/Playstation2/InpMouse]
      - [0x347D88, .rodata, FGDK3/Code/Playstation2/InpKeybd]
      - [0x347EA8, .rodata, FGDK3/Code/Playstation2/InpJoys1]
      - [0x347FA8, .rodata, FGDK3/Code/Playstation2/InpJoy5]
      - [0x347FF0, .rodata, FGDK3/Code/Inpevent]
      - [0x348110, .rodata, FGDK3/Code/Inpdev]
      - [0x3481A0, .rodata, text_002FBD40]
      - [0x348290, .rodata, FGDK3/Code/Playstation2/Controller]

      #File
      #Playstation2/File
      #FileSystem_Zip
      #File_FileDescriptor
      - [0x348390, .rodata, text_002FCF70]
      #-[0x3484F0, .rodata, FGDK3/Code/Playstation2/File_Memcard]
      - [0x348880, .rodata, FGDK3/Code/Playstation2/File_CD]
      - [0x348A30, .rodata, FGDK3/Code/File]
      - [0x348A80, .rodata, text_00307D30]
      - [0x348CD0, .rodata, text_00309778]
      - [0x348CF8, .rodata, FGDK3/Code/StringUtils]
      - [0x348D20, .rodata, FGDK3/Code/ShapeParams]
      - [0x349040, .rodata, FGDK3/Code/FileSystem_Zip]
      - [0x349540, .rodata, text_00315F28] # zlib stuff?
      - [0x349C08, .rodata, FGDK3/ResLibs/AnimRes/Code/AnimRes]
      - [0x349DF0, .rodata, FGDK3/ResLibs/ScriptRes/Code/ScriptThread]
      - [0x34A2E0, .rodata, FGDK3/ResLibs/ScriptRes/Code/ScriptRes]
      - [0x34A820, .rodata, FGDK3/ResLibs/ShapeRes/Code/ShapeRes]
      - [0x34A9A8, .rodata, FGDK3/ResLibs/LandscapeRes/Code/LandscapeRes]
      - [0x34AB88, .rodata, FGDK3/ResLibs/TextureRes/Code/TextureRes]
      - [0x34AC70, .rodata, text_0031FC50]
      - [0x34B180, rodata, sce/eecdvd] # libcdvd
      - [0x34B490, rodata, sce/text_00329C38] # libgraph
      - [0x34B6D8, rodata, sce/libdma]
      - [0x34B750, .rodata, text_0032BC90] # libdev
      - [0x34B788, rodata, sce/libpad]

      - [0x34B8E0, rodata, sce/sdr_main] # libsdr
      - [0x34B908, rodata, sce/sdr_cb]

      - [0x34B930, rodata, sce/libmc]
      - [0x34B9B8, rodata, sce/libscf]
      - [0x34B9E0, .rodata, text_00330930]
      - [0x34C0E8, .rodata, text_00334BD0]



      - [0x34D580, gcc_except_table]
      - [0x34D700, sdata]
      - {start: 0x354280, type: sbss, vram: 0x00453280}
      - {start: 0x354A80, type: bss,  vram: 0x00453A80}

  - [0x360F18, databin]
  - [0x362668]
